### ISSUE TITLE
Practice Task -- Uyseok Lee

### ISSUE THREAD

**Issue by uyseoklee** [uyseoklee/template#1]
# Practice Task 

## Update - July 16th, 2019
* Simulate 1000 draws from a multivariate random normal distribution and save as a .csv
* Scatter the draws and create a line of best fit
* All while following GSLab protocols

### Checklist 

* Read through [RA manual](https://github.com/gslab-econ/ra-manual) carefully.
* Set up your computer properly using the [computer build sheet](https://github.com/gslab-econ/admin/blob/9e5bafed3119856ed2cbf872f58edc4184f12c60/computer-build-sheet/package_build.sh) and Homebrew per RA manual. 

### Task Description

Make sure you follow all procedures in the RA manual (e.g., issue threads, branching, and [time tracking](https://github.com/gslab-econ/admin/wiki/Time-Tracking)).

* Create your own public repository from the [lab template](https://github.com/gslab-econ/template).
* Modify the code to execute `analysis/source/prepare_data/create_data.r`. Run and commit.
* Modify the code to execute `analysis/source/prepare_data/create_data.do`. Run and commit.
* Load external raw data from this [Dropbox directory](https://www.dropbox.com/sh/z694st8vyuwp1o4/AAAKYQmEJIMN5Cmws0N2mbJWa?dl=0) into `analysis` following the guidelines in the template.
* Modify the code so that targets in `analysis/build/descriptive` use the data from Dropbox.
* Modify the code in `paper_slides` to use the new output of `analysis`.
* Run all the code in `analysis` and `paper_slides` and commit. 
* Complete the task. Invite the practice task assigner as a collaborator on your GitHub repo and ask them for peer review.

**Comment by DavidRitzwoller** [comment]
Thanks @uyseoklee. Typically we would like to save the plot in `release` into its own directory mirroring the structure of `source`. Check out ad-price-drivers for examples. In this case `mwn-plots.pdf` should go into `release/mvn-plot` etc.

**Comment by DavidRitzwoller** [comment]
@uyseoklee. The data for the practice task is [here.](https://github.com/uyseoklee/template/files/3402921/data.txt).

**Comment by uyseoklee** [comment]
@DavidRitzwoller I'm having a bit of trouble updating the table and figure in the `paper_slides` folder. My issue is that I am not sure what code to change to update the files in the `paper_slides/input` folder to reflect the new results in the `analysis` directory. I believe all the Scons scripts are written such that the working directory must be the `paper_slides` folder to run the code and I can't seem to find a script here to update the results. (If I want to call the new results, they are in a different directory). I don't think I was supposed to just manually move them into the `inpupt` folder as the instructions said "modify code in paper_slides to use new output of analysis". Do you have a suggestion? I was thinking maybe change all the SConstruct files to have the working directory required be one level higher - `template', instead of `analysis' or `paper_slides' but this seems like too much change.
